# Generated by Django 3.2.5 on 2021-07-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediatitle', models.CharField(default='notitle', max_length=30)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howoldweretheyapp.celebrity')),
            ],
        ),
    ]
