# Generated by Django 3.2.5 on 2021-07-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howoldweretheyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='characters',
            field=models.ForeignKey(default='no characters', on_delete=django.db.models.deletion.CASCADE, to='howoldweretheyapp.celebrity'),
        ),
    ]
